var state={currentUser:null,users:[],tasks:[],notifications:[],taskFilter:'all',assignedFilter:'all',searchQuery:'',editingTaskId:null};
var COLORS=['c1','c2','c3','c4','c5','c6','c7','c8'];
var PIE_COLORS=['#1a3a6b','#e8621a','#2a5fa8','#c0392b','#16a085','#8e44ad','#2980b9','#e67e22'];

function save(){localStorage.setItem('tfp_users',JSON.stringify(state.users));localStorage.setItem('tfp_tasks',JSON.stringify(state.tasks));localStorage.setItem('tfp_notifs',JSON.stringify(state.notifications));}

function load(){
  var u=localStorage.getItem('tfp_users');
  var t=localStorage.getItem('tfp_tasks');
  var n=localStorage.getItem('tfp_notifs');
  state.users=u?JSON.parse(u):[];
  state.tasks=t?JSON.parse(t):[];
  state.notifications=n?JSON.parse(n):[];
  var demoUsers=[
    {id:'u1',name:'Admin Demo',email:'admin_demo',password:'admin123',role:'manager',color:'c1'},
    {id:'u2',name:'Giulia Bianchi',email:'giulia_demo',password:'pass123',role:'member',color:'c2'},
    {id:'u3',name:'Marco Verdi',email:'marco_demo',password:'pass123',role:'member',color:'c3'},
    {id:'u4',name:'Sara Neri',email:'sara_demo',password:'pass123',role:'member',color:'c4'}
  ];
  demoUsers.forEach(function(du){if(!state.users.find(function(x){return x.email===du.email;}))state.users.push(du);});
  var today=new Date();
  var d=function(o){var x=new Date(today);x.setDate(x.getDate()+o);return x.toISOString().split('T')[0];};
  var demoTasks=[
    {id:'t1',title:'Preparare presentazione Q2',desc:'Slide per il board meeting',assignee:'u2',coAssignee:'u3',subAssignee:'',priority:'high',dueDate:d(2),dueTime:'18:00',reminder:'1d',list:'Management',notes:'',status:'open',createdBy:'u1',createdAt:new Date().toISOString(),completedAt:null,comments:[],readBy:['u1']},
    {id:'t2',title:'Aggiornare documentazione API',desc:'',assignee:'u3',coAssignee:'',subAssignee:'u4',priority:'medium',dueDate:d(5),dueTime:'18:00',reminder:'2d',list:'Dev',notes:'',status:'open',createdBy:'u1',createdAt:new Date().toISOString(),completedAt:null,comments:[],readBy:['u1']},
    {id:'t3',title:'Review contratto fornitore',desc:'Verificare clausole 3 e 7',assignee:'u4',coAssignee:'',subAssignee:'',priority:'high',dueDate:d(-1),dueTime:'18:00',reminder:'',list:'Legal',notes:'',status:'open',createdBy:'u1',createdAt:new Date().toISOString(),completedAt:null,comments:[],readBy:['u1']},
    {id:'t4',title:'Onboarding nuovo cliente',desc:'',assignee:'u2',coAssignee:'u4',subAssignee:'',priority:'medium',dueDate:d(10),dueTime:'18:00',reminder:'3d',list:'Sales',notes:'',status:'completed',createdBy:'u1',createdAt:new Date().toISOString(),completedAt:new Date().toISOString(),comments:[],readBy:['u1','u2','u4']},
    {id:'t5',title:'Analisi competitor Q2',desc:'Report settimanale',assignee:'u1',coAssignee:'',subAssignee:'',priority:'low',dueDate:d(7),dueTime:'18:00',reminder:'1d',list:'Marketing',notes:'',status:'open',createdBy:'u1',createdAt:new Date().toISOString(),completedAt:null,comments:[],readBy:['u1']}
  ];
  demoTasks.forEach(function(dt){if(!state.tasks.find(function(x){return x.id===dt.id;}))state.tasks.push(dt);});
  save();
}

function doLogin(){
  var email=document.getElementById('loginEmail').value.trim();
  var pass=document.getElementById('loginPassword').value;
  if(!email||!pass){showLoginError('Inserisci username e password.');return;}
  var userExists=state.users.find(function(u){return u.email===email;});
  if(!userExists){showLoginError('Nessun account trovato. Registrati prima!');return;}
  var user=state.users.find(function(u){return u.email===email&&u.password===pass;});
  if(!user){showLoginError('Password errata. Riprova!');return;}
  hideLoginError();
  state.currentUser=user;
  localStorage.setItem('tfp_session',user.id);
  bootApp();
}

function showLoginError(msg){
  var el=document.getElementById('loginError');
  if(!el){el=document.createElement('div');el.id='loginError';el.style.cssText='background:rgba(192,57,43,0.1);border:1px solid rgba(192,57,43,0.3);border-radius:8px;padding:10px 14px;font-size:13px;color:#c0392b;margin-bottom:14px;text-align:center;';document.getElementById('loginForm').insertBefore(el,document.getElementById('loginForm').firstChild);}
  el.textContent=msg;el.style.display='block';
}
function hideLoginError(){var el=document.getElementById('loginError');if(el)el.style.display='none';}

function doRegister(){
  var name=document.getElementById('regName').value.trim();
  var email=document.getElementById('regEmail').value.trim();
  var pass=document.getElementById('regPassword').value;
  if(!name||!email||!pass){showNotif('Compila tutti i campi','error');return;}
  if(pass.length<6){showNotif('Password troppo corta (min 6)','error');return;}
  if(state.users.find(function(u){return u.email===email;})){showNotif('Username già registrato','error');return;}
  var user={id:'u'+Date.now(),name:name,email:email,password:pass,role:'member',color:COLORS[state.users.length%COLORS.length]};
  state.users.push(user);state.currentUser=user;localStorage.setItem('tfp_session',user.id);save();bootApp();
}

function doLogout(){state.currentUser=null;localStorage.removeItem('tfp_session');document.getElementById('appMain').style.display='none';document.getElementById('loginScreen').style.display='flex';}

function bootApp(){
  document.getElementById('loginScreen').style.display='none';document.getElementById('appMain').style.display='flex';
  var u=state.currentUser;
  document.getElementById('sidebarAvatar').textContent=u.name[0].toUpperCase();
  document.getElementById('sidebarAvatar').className='user-avatar '+u.color;
  document.getElementById('sidebarName').textContent=u.name;
  document.getElementById('sidebarRole').textContent=u.role==='manager'?'Manager':'Team Member';
  if(u.role==='manager'){document.getElementById('adminSection').style.display='block';document.getElementById('usersNav').style.display='flex';}
  showView('dashboard');checkReminders();setInterval(checkReminders,60000);
}

function showView(name){
  document.querySelectorAll('.view').forEach(function(v){v.classList.remove('active');});
  document.querySelectorAll('.nav-item').forEach(function(n){n.classList.remove('active');});
  document.getElementById('view-'+name).classList.add('active');
  document.querySelectorAll('.nav-item').forEach(function(n){if(n.getAttribute('onclick')&&n.getAttribute('onclick').includes(name))n.classList.add('active');});
  document.getElementById('sidebar').classList.remove('open');
  var titles={dashboard:'Dashboard',tasks:'I miei Task',assigned:'Task Assegnati',byAssignee:'Per Assegnatario',byDueDate:'Per Scadenza',reminders:'Reminder',analytics:'Statistiche',users:'Gestione Utenti'};
  document.getElementById('topbarTitle').textContent=titles[name]||name;
  updateBadges();
  if(name==='dashboard')renderDashboard();
  if(name==='tasks')renderMyTasks();
  if(name==='assigned')renderAssigned();
  if(name==='byAssignee')renderByAssignee();
  if(name==='byDueDate')renderByDueDate();
  if(name==='reminders')renderReminders();
  if(name==='analytics')renderAnalytics();
  if(name==='users')renderUsers();
}

function toggleSidebar(){document.getElementById('sidebar').classList.toggle('open');}

function updateBadges(){
  var u=state.currentUser;
  document.getElementById('myTasksBadge').textContent=state.tasks.filter(function(t){return t.assignee===u.id&&t.status==='open';}).length;
  document.getElementById('assignedBadge').textContent=state.tasks.filter(function(t){return t.createdBy===u.id&&t.assignee!==u.id;}).length;
  document.getElementById('reminderBadge').textContent=state.notifications.filter(function(n){return !n.read&&n.userId===u.id;}).length;
}

function renderDashboard(){
  var u=state.currentUser;var today=new Date();today.setHours(0,0,0,0);
  var allTasks=u.role==='manager'?state.tasks:state.tasks.filter(function(t){return t.assignee===u.id||t.coAssignee===u.id||t.subAssignee===u.id||t.createdBy===u.id;});
  var overdue=allTasks.filter(function(t){return t.status==='open'&&new Date(t.dueDate)<today;});
  var completed=allTasks.filter(function(t){return t.status==='completed';});
  var open=allTasks.filter(function(t){return t.status==='open';});
  var stats=[{label:'Totali',value:allTasks.length,icon:'📋',color:'var(--accent)'},{label:'Aperti',value:open.length,icon:'🔵',color:'var(--accent2)'},{label:'Completati',value:completed.length,icon:'✅',color:'var(--accent3)'}];
  document.getElementById('statsGrid').innerHTML=stats.map(function(s){return '<div class="stat-card" style="--accent-color:'+s.color+'"><div class="stat-value" style="color:'+s.color+'">'+s.value+'</div><div class="stat-label">'+s.label+'</div><div class="stat-icon">'+s.icon+'</div></div>';}).join('');
  var myCreated=state.tasks.filter(function(t){return t.createdBy===u.id&&t.assignee!==u.id;});
  var unread=myCreated.filter(function(t){return !t.readBy||!t.readBy.includes(t.assignee);});
  var unreadIds=[...new Set(unread.map(function(t){return t.assignee;}).filter(Boolean))];
  document.getElementById('unreadCount').textContent='('+unread.length+')';
  document.getElementById('unreadList').innerHTML=unread.length?unreadIds.map(function(uid){var au=getUserById(uid);if(!au)return'';var tasks=unread.filter(function(t){return t.assignee===uid;});var gid='unread_'+uid;return'<div style="margin-bottom:8px"><div style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;background:var(--surface2);border-radius:var(--radius-sm);cursor:pointer" onclick="toggleDashGroup(''+gid+'')"><div style="display:flex;align-items:center;gap:8px"><div class="user-avatar '+au.color+'" style="width:26px;height:26px;font-size:11px">'+au.name[0]+'</div><span style="font-weight:600;font-size:13px">'+au.name+'</span><span class="unread-badge">'+tasks.length+'</span></div><span id="'+gid+'-icon" style="font-size:18px;color:var(--accent);font-weight:700">+</span></div><div id="'+gid+'-body" style="display:none;padding:4px 0">'+tasks.map(function(t){return'<div class="task-item" style="margin:4px 0" onclick="openTaskDetail(''+t.id+'')"><div class="task-body"><div class="task-title">'+t.title+'</div><div class="task-meta">'+dueDateTag(t.dueDate)+'</div></div><button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();openQuickReminder(''+t.id+'',event)" style="color:var(--warning);white-space:nowrap">🔔 Sollecita</button></div>';}).join('')+'</div></div>';}).join(''):'<div class="empty-state" style="padding:16px"><p style="font-size:13px">Tutti letti ✅</p></div>';
  var ovIds=[...new Set(overdue.map(function(t){return t.assignee;}).filter(Boolean))];
  document.getElementById('overdueCount').textContent='('+overdue.length+')';
  document.getElementById('overdueList').innerHTML=overdue.length?ovIds.map(function(uid){var au=getUserById(uid);if(!au)return'';var tasks=overdue.filter(function(t){return t.assignee===uid;});var gid='overdue_'+uid;return'<div style="margin-bottom:8px"><div style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;background:rgba(192,57,43,0.07);border-radius:var(--radius-sm);cursor:pointer;border-left:3px solid var(--danger)" onclick="toggleDashGroup(''+gid+'')"><div style="display:flex;align-items:center;gap:8px"><div class="user-avatar '+au.color+'" style="width:26px;height:26px;font-size:11px">'+au.name[0]+'</div><span style="font-weight:600;font-size:13px">'+au.name+'</span><span style="background:rgba(192,57,43,0.15);color:var(--danger);font-size:11px;font-weight:700;border-radius:20px;padding:2px 7px">'+tasks.length+' scaduti</span></div><span id="'+gid+'-icon" style="font-size:18px;color:var(--danger);font-weight:700">+</span></div><div id="'+gid+'-body" style="display:none;padding:4px 0">'+tasks.map(function(t){return'<div class="task-item overdue" style="margin:4px 0" onclick="openTaskDetail(''+t.id+'')"><div class="task-body"><div class="task-title">'+t.title+'</div><div class="task-meta">'+dueDateTag(t.dueDate)+'</div></div><button class="btn btn-danger btn-sm" onclick="event.stopPropagation();openQuickReminder(''+t.id+'',event)" style="white-space:nowrap">🔔 Sollecita</button></div>';}).join('')+'</div></div>';}).join(''):'<div class="empty-state" style="padding:16px"><p style="font-size:13px">Nessun scaduto 🎉</p></div>';
  var myTasks=state.tasks.filter(function(t){return t.assignee===u.id||t.coAssignee===u.id||t.subAssignee===u.id;});
  var assignedByMe=state.tasks.filter(function(t){return t.createdBy===u.id&&t.assignee!==u.id;});
  var assigneeIds=[...new Set(assignedByMe.map(function(t){return t.assignee;}).filter(Boolean))];
  var html='<div class="card" style="margin-top:4px"><div class="card-header" style="cursor:pointer" onclick="toggleDashGroup('myTasks')"><div style="display:flex;align-items:center;gap:10px"><div class="user-avatar '+u.color+'" style="width:30px;height:30px;font-size:12px">'+u.name[0]+'</div><div><div class="card-title">📋 I miei Task</div><div style="font-size:12px;color:var(--text3)">'+myTasks.filter(function(t){return t.status==='open';}).length+' aperti · '+myTasks.filter(function(t){return t.status==='completed';}).length+' completati</div></div></div><span id="myTasks-icon" style="font-size:22px;color:var(--accent);font-weight:700;line-height:1">−</span></div><div id="myTasks-body">'+(myTasks.length?myTasks.map(function(t){return taskCard(t);}).join(''):'<p style="color:var(--text3);font-size:13px;padding:8px">Nessun task assegnato a te</p>')+'</div></div>';
  assigneeIds.forEach(function(uid){var au=getUserById(uid);if(!au)return;var tasks=assignedByMe.filter(function(t){return t.assignee===uid;});var oc=tasks.filter(function(t){return t.status==='open';}).length;var dc=tasks.filter(function(t){return t.status==='completed';}).length;var ovc=tasks.filter(function(t){return t.status==='open'&&new Date(t.dueDate)<today;}).length;var uc=tasks.filter(function(t){return !t.readBy||!t.readBy.includes(uid);}).length;var gid='group_'+uid;html+='<div class="card" style="margin-top:10px"><div class="card-header" style="cursor:pointer" onclick="toggleDashGroup(''+gid+'')"><div style="display:flex;align-items:center;gap:10px"><div class="user-avatar '+au.color+'" style="width:30px;height:30px;font-size:12px">'+au.name[0]+'</div><div><div style="display:flex;align-items:center;gap:8px"><div class="card-title">'+au.name+'</div>'+(uc>0?'<span class="unread-badge">● '+uc+' non letti</span>':'')+'</div><div style="font-size:12px;color:var(--text3)">'+oc+' aperti · '+dc+' completati'+(ovc>0?' · <span style="color:var(--danger)">'+ovc+' scaduti</span>':'')+'</div></div></div><span id="'+gid+'-icon" style="font-size:22px;color:var(--accent);font-weight:700;line-height:1">+</span></div><div id="'+gid+'-body" style="display:none">'+tasks.map(function(t){return taskCard(t);}).join('')+'</div></div>';});
  document.getElementById('recentActivity').innerHTML=html;
}

function toggleDashGroup(id){var body=document.getElementById(id+'-body');var icon=document.getElementById(id+'-icon');if(!body)return;var isOpen=body.style.display!=='none';body.style.display=isOpen?'none':'block';icon.textContent=isOpen?'+':'−';}

function renderMyTasks(){var u=state.currentUser;var tasks=state.tasks.filter(function(t){return t.assignee===u.id||t.coAssignee===u.id||t.subAssignee===u.id;});tasks=applyFilter(tasks,state.taskFilter);if(state.searchQuery)tasks=tasks.filter(function(t){return t.title.toLowerCase().includes(state.searchQuery.toLowerCase());});document.getElementById('myTasksList').innerHTML=tasks.length?tasks.map(function(t){return taskCard(t);}).join(''):emptyState('Nessun task','Crea un nuovo task!');}
function filterTasks(el,f){state.taskFilter=f;document.querySelectorAll('#view-tasks .filter-chip').forEach(function(c){c.classList.remove('active');});el.classList.add('active');renderMyTasks();}
function searchTasks(q){state.searchQuery=q;renderMyTasks();}

function renderAssigned(){var u=state.currentUser;var tasks=applyFilter(state.tasks.filter(function(t){return t.createdBy===u.id;}),state.assignedFilter);document.getElementById('assignedList').innerHTML=tasks.length?tasks.map(function(t){return taskCard(t);}).join(''):emptyState('Nessun task assegnato','Crea un task!');}
function filterAssigned(el,f){state.assignedFilter=f;document.querySelectorAll('#view-assigned .filter-chip').forEach(function(c){c.classList.remove('active');});el.classList.add('active');renderAssigned();}

function renderByAssignee(){var u=state.currentUser;var content=document.getElementById('byAssigneeContent');var tasks=u.role==='manager'?state.tasks:state.tasks.filter(function(t){return t.createdBy===u.id;});var ids=[...new Set(tasks.map(function(t){return t.assignee;}).filter(Boolean))];if(!ids.length){content.innerHTML=emptyState('Nessun task assegnato','');return;}var today=new Date();today.setHours(0,0,0,0);content.innerHTML=ids.map(function(uid){var au=getUserById(uid);if(!au)return'';var ts=tasks.filter(function(t){return t.assignee===uid;});var done=ts.filter(function(t){return t.status==='completed';}).length;var ov=ts.filter(function(t){return t.status==='open'&&new Date(t.dueDate)<today;}).length;var pct=ts.length?Math.round(done/ts.length*100):0;return'<div class="assignee-group"><div class="assignee-header"><div class="user-avatar '+au.color+'" style="width:34px;height:34px;font-size:12px">'+au.name[0]+'</div><div><div style="font-weight:600;font-size:14px">'+au.name+'</div><div style="font-size:11px;color:var(--text3)">'+au.email+'</div></div><div class="assignee-count">'+ts.length+' task · <span style="color:var(--accent3)">'+done+' fatti</span>'+(ov>0?' · <span style="color:var(--danger)">'+ov+' scaduti</span>':'')+'</div></div><div class="progress-bar"><div class="progress-fill" style="width:'+pct+'%"></div></div><div style="margin-top:10px">'+ts.map(function(t){return taskCard(t);}).join('')+'</div></div>';}).join('');}

function renderByDueDate(){var u=state.currentUser;var tasks=u.role==='manager'?state.tasks:state.tasks.filter(function(t){return t.assignee===u.id||t.createdBy===u.id;});var today=new Date();today.setHours(0,0,0,0);var groups=[{label:'🔴 Scaduti',tasks:tasks.filter(function(t){return t.status==='open'&&new Date(t.dueDate)<today;}).sort(function(a,b){return new Date(a.dueDate)-new Date(b.dueDate);})},{label:'⚡ Oggi',tasks:tasks.filter(function(t){var d=new Date(t.dueDate);d.setHours(0,0,0,0);return d.getTime()===today.getTime();})},{label:'📅 Questa settimana',tasks:tasks.filter(function(t){var diff=(new Date(t.dueDate)-today)/86400000;return diff>0&&diff<=7;}).sort(function(a,b){return new Date(a.dueDate)-new Date(b.dueDate);})},{label:'📆 Prossime settimane',tasks:tasks.filter(function(t){return(new Date(t.dueDate)-today)/86400000>7;}).sort(function(a,b){return new Date(a.dueDate)-new Date(b.dueDate);})},{label:'✅ Completati',tasks:tasks.filter(function(t){return t.status==='completed';}).sort(function(a,b){return new Date(b.completedAt)-new Date(a.completedAt);})}];document.getElementById('byDueDateContent').innerHTML=groups.map(function(g){return g.tasks.length?'<div class="section-label">'+g.label+' <span style="color:var(--text3);font-size:11px">'+g.tasks.length+'</span></div>'+g.tasks.map(function(t){return taskCard(t);}).join(''):''}).join('');}

function renderReminders(){var sel=document.getElementById('reminderTaskSelect');sel.innerHTML=state.tasks.filter(function(t){return t.status==='open';}).map(function(t){return'<option value="'+t.id+'">'+t.title+'</option>';}).join('');var notifs=state.notifications.filter(function(n){return n.userId===state.currentUser.id;});document.getElementById('remindersList').innerHTML=notifs.length?notifs.sort(function(a,b){return new Date(b.createdAt)-new Date(a.createdAt);}).map(function(n){return'<div class="reminder-banner" style="'+(n.read?'opacity:0.5':'')+'"><span class="icon">'+(n.read?'📭':'🔔')+'</span><div style="flex:1"><div style="font-weight:500;font-size:13px">'+n.message+'</div><div style="font-size:11px;color:var(--text3);margin-top:3px">'+formatDate(n.createdAt)+'</div></div>'+(n.read?'':'<button class="btn btn-ghost btn-sm" onclick="markNotifRead(''+n.id+'')">✓ Letto</button>')+'</div>';}).join(''):'<p style="color:var(--text3);font-size:13px">Nessun reminder</p>';}
function sendManualReminder(){var taskId=document.getElementById('reminderTaskSelect').value;var msg=document.getElementById('reminderMessage').value.trim();if(!taskId){showNotif('Seleziona un task','error');return;}var task=state.tasks.find(function(t){return t.id===taskId;});if(!task)return;var message=msg||'⏰ Reminder: "'+task.title+'" scade il '+task.dueDate;[task.assignee,task.coAssignee,task.subAssignee].filter(Boolean).forEach(function(uid){addNotification(uid,message,taskId);});document.getElementById('reminderMessage').value='';showNotif('Reminder inviato!','success');renderReminders();}
function markNotifRead(id){var n=state.notifications.find(function(x){return x.id===id;});if(n){n.read=true;save();renderReminders();updateBadges();}}
function addNotification(userId,message,taskId){state.notifications.push({id:'n'+Date.now()+Math.random(),userId:userId,message:message,taskId:taskId||null,createdAt:new Date().toISOString(),read:false});save();updateBadges();if(userId===state.currentUser.id)showNotif(message,'warning');}
function checkReminders(){var now=new Date();state.tasks.filter(function(t){return t.status==='open'&&t.reminder;}).forEach(function(task){var due=new Date(task.dueDate+'T'+(task.dueTime||'18:00'));var diffMs=due-now;var diffH=diffMs/3600000;var thresh={'1h':1,'3h':3,'1d':24,'2d':48,'3d':72,'1w':168}[task.reminder];if(!thresh)return;var key='rem_'+task.id+'_'+task.reminder;if(diffH>0&&diffH<=thresh&&!localStorage.getItem(key)){localStorage.setItem(key,'1');[task.assignee,task.coAssignee,task.subAssignee].filter(Boolean).forEach(function(uid){addNotification(uid,'⏰ Reminder: "'+task.title+'" scade presto',task.id);});}if(diffMs<0){var ok='overdue_'+task.id;if(!localStorage.getItem(ok)){localStorage.setItem(ok,'1');[task.assignee,task.coAssignee,task.subAssignee].filter(Boolean).forEach(function(uid){addNotification(uid,'🚨 SCADUTO: "'+task.title+'"',task.id);});}}});}

function renderAnalytics(){var u=state.currentUser;var tasks=u.role==='manager'?state.tasks:state.tasks.filter(function(t){return t.assignee===u.id||t.createdBy===u.id;});var byA={};tasks.forEach(function(t){var usr=getUserById(t.assignee);var nm=usr?usr.name.split(' ')[0]:'?';byA[nm]=(byA[nm]||0)+1;});drawPie(byA);var today=new Date();today.setHours(0,0,0,0);var total=tasks.length||1;document.getElementById('statusBars').innerHTML=[{label:'Aperti',value:tasks.filter(function(t){return t.status==='open';}).length,color:'var(--accent2)'},{label:'Completati',value:tasks.filter(function(t){return t.status==='completed';}).length,color:'var(--accent3)'},{label:'Scaduti',value:tasks.filter(function(t){return t.status==='open'&&new Date(t.dueDate)<today;}).length,color:'var(--danger)'}].map(function(s){return'<div style="margin-bottom:14px"><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:6px"><span>'+s.label+'</span><span style="color:'+s.color+';font-weight:600">'+s.value+'</span></div><div class="progress-bar" style="height:8px"><div class="progress-fill" style="width:'+Math.round(s.value/total*100)+'%;background:'+s.color+'"></div></div></div>';}).join('');var users=state.users.filter(function(u){return state.tasks.some(function(t){return t.assignee===u.id;});});document.getElementById('performanceTable').innerHTML='<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr style="color:var(--text3);text-align:left"><th style="padding:8px 0;border-bottom:1px solid var(--border)">Utente</th><th style="padding:8px 0;border-bottom:1px solid var(--border)">Task</th><th style="padding:8px 0;border-bottom:1px solid var(--border)">Fatti</th><th style="padding:8px 0;border-bottom:1px solid var(--border)">%</th></tr></thead><tbody>'+users.map(function(usr){var ut=tasks.filter(function(t){return t.assignee===usr.id;});var ud=ut.filter(function(t){return t.status==='completed';}).length;var pct=ut.length?Math.round(ud/ut.length*100):0;return'<tr><td style="padding:10px 0;border-bottom:1px solid var(--border)"><div style="display:flex;align-items:center;gap:8px"><div class="user-avatar '+usr.color+'" style="width:28px;height:28px;font-size:11px">'+usr.name[0]+'</div>'+usr.name+'</div></td><td style="padding:10px 0;border-bottom:1px solid var(--border)">'+ut.length+'</td><td style="padding:10px 0;border-bottom:1px solid var(--border);color:var(--accent3)">'+ud+'</td><td style="padding:10px 0;border-bottom:1px solid var(--border)"><div style="display:flex;align-items:center;gap:8px"><div class="progress-bar" style="flex:1;height:6px"><div class="progress-fill" style="width:'+pct+'%"></div></div><span style="font-size:12px;color:var(--accent3)">'+pct+'%</span></div></td></tr>';}).join('')+'</tbody></table>';}

function drawPie(data){var svg=document.getElementById('pieChart');var legend=document.getElementById('pieLegend');var entries=Object.entries(data);var total=entries.reduce(function(s,e){return s+e[1];},0)||1;var angle=-Math.PI/2;var cx=80,cy=80,r=65;svg.innerHTML=entries.map(function(e,i){var pct=e[1]/total;var a1=angle,a2=angle+pct*2*Math.PI;angle=a2;var x1=cx+r*Math.cos(a1),y1=cy+r*Math.sin(a1),x2=cx+r*Math.cos(a2),y2=cy+r*Math.sin(a2);return'<path d="M'+cx+','+cy+' L'+x1+','+y1+' A'+r+','+r+' 0 '+(pct>0.5?1:0)+',1 '+x2+','+y2+' Z" fill="'+PIE_COLORS[i%PIE_COLORS.length]+'" stroke="var(--bg)" stroke-width="2"/>';}).join('')+'<circle cx="'+cx+'" cy="'+cy+'" r="30" fill="var(--surface)"/><text x="'+cx+'" y="'+(cy+5)+'" text-anchor="middle" fill="var(--text2)" font-size="13">'+total+'</text>';legend.innerHTML=entries.map(function(e,i){return'<div class="pie-legend-item"><div class="pie-legend-dot" style="background:'+PIE_COLORS[i%PIE_COLORS.length]+'"></div><span>'+e[0]+' — <strong>'+e[1]+'</strong></span></div>';}).join('');}

function renderUsers(){document.getElementById('usersList').innerHTML=state.users.map(function(u){return'<div style="display:flex;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid var(--border)"><div class="user-avatar '+u.color+'">'+u.name[0]+'</div><div style="flex:1"><div style="font-weight:500;font-size:14px">'+u.name+'</div><div style="font-size:12px;color:var(--text3)">'+u.email+' — '+u.role+'</div></div><span style="font-size:12px;color:var(--text2);margin-right:8px">'+state.tasks.filter(function(t){return t.assignee===u.id;}).length+' task</span><button class="btn btn-ghost btn-sm" onclick="adminResetPassword(''+u.id+'')">🔑 Reset</button></div>';}).join('');}

function openCreateUser(){document.getElementById('newUserName').value='';document.getElementById('newUserEmail').value='';document.getElementById('newUserPassword').value='';document.getElementById('newUserRole').value='member';document.getElementById('createUserError').style.display='none';document.getElementById('createUserSuccess').style.display='none';document.getElementById('createUserBtn').style.display='inline-flex';openModal('createUserModal');}
function createUser(){var name=document.getElementById('newUserName').value.trim();var email=document.getElementById('newUserEmail').value.trim();var password=document.getElementById('newUserPassword').value.trim();var role=document.getElementById('newUserRole').value;var errEl=document.getElementById('createUserError');errEl.style.display='none';if(!name||!email||!password){errEl.textContent='Compila tutti i campi';errEl.style.display='block';return;}if(password.length<6){errEl.textContent='Password troppo corta';errEl.style.display='block';return;}if(state.users.find(function(u){return u.email===email;})){errEl.textContent='Username già usato';errEl.style.display='block';return;}var nu={id:'u'+Date.now(),name:name,email:email,password:password,role:role,color:COLORS[state.users.length%COLORS.length]};state.users.push(nu);save();document.getElementById('createUserCredentials').innerHTML='🌐 Link: <strong>'+window.location.href+'</strong><br>👤 Username: <strong>'+email+'</strong><br>🔑 Password: <strong>'+password+'</strong>';document.getElementById('createUserSuccess').style.display='block';document.getElementById('createUserBtn').style.display='none';renderUsers();showNotif('Utente '+name+' creato!','success');}
function adminResetPassword(userId){var user=state.users.find(function(u){return u.id===userId;});if(!user)return;var newPwd=prompt('Nuova password per '+user.name+':');if(!newPwd)return;if(newPwd.length<6){showNotif('Password troppo corta!','error');return;}user.password=newPwd;save();showNotif('Password aggiornata!','success');}

function openNewTask(){state.editingTaskId=null;document.getElementById('taskModalTitle').textContent='Nuovo Task';['taskId','taskTitle','taskDesc','taskNotes','taskList'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('taskPriority').value='medium';document.getElementById('taskReminder').value='';document.getElementById('taskDueDate').value='';document.getElementById('taskDueTime').value='18:00';populateAssigneeSelects(null);openModal('taskModal');}
function populateAssigneeSelects(task){['taskAssignee','taskCoAssignee','taskSubAssignee'].forEach(function(id,idx){var sel=document.getElementById(id);var opts=idx===0?state.users:[{id:'',name:'-- Nessuno --'}].concat(state.users);sel.innerHTML=opts.map(function(u){return'<option value="'+u.id+'">'+u.name+'</option>';}).join('');if(task){if(id==='taskAssignee')sel.value=task.assignee||'';if(id==='taskCoAssignee')sel.value=task.coAssignee||'';if(id==='taskSubAssignee')sel.value=task.subAssignee||'';}});}
function editTask(id){var task=state.tasks.find(function(t){return t.id===id;});if(!task)return;state.editingTaskId=id;document.getElementById('taskModalTitle').textContent='Modifica Task';document.getElementById('taskId').value=id;document.getElementById('taskTitle').value=task.title;document.getElementById('taskDesc').value=task.desc||'';document.getElementById('taskNotes').value=task.notes||'';document.getElementById('taskList').value=task.list||'';document.getElementById('taskPriority').value=task.priority||'medium';document.getElementById('taskReminder').value=task.reminder||'';document.getElementById('taskDueDate').value=task.dueDate||'';document.getElementById('taskDueTime').value=task.dueTime||'18:00';populateAssigneeSelects(task);closeModal('detailModal');openModal('taskModal');}
function saveTask(){var title=document.getElementById('taskTitle').value.trim();var assignee=document.getElementById('taskAssignee').value;var dueDate=document.getElementById('taskDueDate').value;if(!title){showNotif('Inserisci un titolo','error');return;}if(!assignee){showNotif('Seleziona un assegnatario','error');return;}if(!dueDate){showNotif('Seleziona una data','error');return;}var td={title:title,desc:document.getElementById('taskDesc').value,assignee:assignee,coAssignee:document.getElementById('taskCoAssignee').value,subAssignee:document.getElementById('taskSubAssignee').value,priority:document.getElementById('taskPriority').value,dueDate:dueDate,dueTime:document.getElementById('taskDueTime').value,reminder:document.getElementById('taskReminder').value,list:document.getElementById('taskList').value,notes:document.getElementById('taskNotes').value};if(state.editingTaskId){var t=state.tasks.find(function(x){return x.id===state.editingTaskId;});Object.assign(t,td);showNotif('Task aggiornato!','success');}else{var nt=Object.assign({id:'t'+Date.now(),status:'open',createdBy:state.currentUser.id,createdAt:new Date().toISOString(),completedAt:null,comments:[],readBy:[state.currentUser.id]},td);state.tasks.push(nt);if(assignee!==state.currentUser.id)addNotification(assignee,'📋 Nuovo task: "'+title+'" scade il '+dueDate,nt.id);if(td.coAssignee&&td.coAssignee!==state.currentUser.id)addNotification(td.coAssignee,'📋 Sei co-assegnatario di: "'+title+'"',nt.id);if(td.subAssignee&&td.subAssignee!==state.currentUser.id)addNotification(td.subAssignee,'📋 Sei sub-assegnatario di: "'+title+'"',nt.id);showNotif('Task creato!','success');}save();closeModal('taskModal');var active=document.querySelector('.view.active');if(active)showView(active.id.replace('view-',''));}
function toggleComplete(id,e){e.stopPropagation();var task=state.tasks.find(function(t){return t.id===id;});if(!task)return;task.status=task.status==='completed'?'open':'completed';task.completedAt=task.status==='completed'?new Date().toISOString():null;save();showNotif(task.status==='completed'?'✅ Completato!':'↩️ Riaperto','success');var active=document.querySelector('.view.active');if(active)showView(active.id.replace('view-',''));}
function deleteTask(id,e){e.stopPropagation();if(!confirm('Eliminare?'))return;state.tasks=state.tasks.filter(function(t){return t.id!==id;});save();showNotif('Task eliminato','success');var active=document.querySelector('.view.active');if(active)showView(active.id.replace('view-',''));}

function openTaskDetail(id){
  var task=state.tasks.find(function(t){return t.id===id;});if(!task)return;
  if(!task.readBy)task.readBy=[];
  if(!task.readBy.includes(state.currentUser.id)){task.readBy.push(state.currentUser.id);save();}
  var a=getUserById(task.assignee),co=getUserById(task.coAssignee),sub=getUserById(task.subAssignee),cr=getUserById(task.createdBy);
  var today=new Date();today.setHours(0,0,0,0);var isOv=task.status==='open'&&new Date(task.dueDate)<today;
  var canComment=[task.assignee,task.coAssignee,task.subAssignee,task.createdBy].includes(state.currentUser.id);
  var comments=task.comments||[];
  document.getElementById('detailBody').innerHTML=
    '<div style="margin-bottom:16px"><h2 style="font-family:Syne,sans-serif;font-size:18px;font-weight:700">'+task.title+'</h2>'+(task.desc?'<p style="color:var(--text2);font-size:14px;margin-top:8px">'+task.desc+'</p>':'')+'</div>'+
    '<div class="detail-row"><div class="detail-key">Status</div><div class="detail-val">'+(task.status==='completed'?'<span style="color:var(--accent3)">✅ Completato</span>':isOv?'<span style="color:var(--danger)">🔴 Scaduto</span>':'<span style="color:var(--accent)">🔵 Aperto</span>')+'</div></div>'+
    '<div class="detail-row"><div class="detail-key">Priorità</div><div class="detail-val">'+priorityTag(task.priority)+'</div></div>'+
    '<div class="detail-row"><div class="detail-key">Scadenza</div><div class="detail-val">📅 '+task.dueDate+(task.dueTime?' alle '+task.dueTime:'')+'</div></div>'+
    '<div class="detail-row"><div class="detail-key">Assegnatario</div><div class="detail-val">'+(a?'<span style="display:flex;align-items:center;gap:6px"><div class="user-avatar '+a.color+'" style="width:22px;height:22px;font-size:10px">'+a.name[0]+'</div>'+a.name+'</span>':'—')+'</div></div>'+
    (co?'<div class="detail-row"><div class="detail-key">Co-assegnatario</div><div class="detail-val"><span style="display:flex;align-items:center;gap:6px"><div class="user-avatar '+co.color+'" style="width:22px;height:22px;font-size:10px">'+co.name[0]+'</div>'+co.name+'</span></div></div>':'')+
    (sub?'<div class="detail-row"><div class="detail-key">Sub-assegnatario</div><div class="detail-val"><span style="display:flex;align-items:center;gap:6px"><div class="user-avatar '+sub.color+'" style="width:22px;height:22px;font-size:10px">'+sub.name[0]+'</div>'+sub.name+'</span></div></div>':'')+
    '<div class="detail-row"><div class="detail-key">Creato da</div><div class="detail-val">'+(cr?cr.name:'—')+'</div></div>'+
    '<div class="detail-row"><div class="detail-key">Creato il</div><div class="detail-val">'+formatDate(task.createdAt)+'</div></div>'+
    (task.reminder?'<div class="detail-row"><div class="detail-key">Reminder</div><div class="detail-val">🔔 '+task.reminder+' prima</div></div>':'')+
    (task.list?'<div class="detail-row"><div class="detail-key">Lista</div><div class="detail-val">📁 '+task.list+'</div></div>':'')+
    (task.notes?'<div class="detail-row"><div class="detail-key">Note</div><div class="detail-val" style="font-style:italic;color:var(--text2)">'+task.notes+'</div></div>':'')+
    '<div style="margin-top:20px"><div style="font-family:Syne,sans-serif;font-weight:700;font-size:14px;margin-bottom:12px">💬 Commenti ('+comments.length+')</div><div id="commentsList">'+(comments.length?comments.map(function(c){var cu=getUserById(c.userId);return'<div class="comment-item"><div class="comment-avatar '+(cu?cu.color:'c1')+'">'+(cu?cu.name[0]:'?')+'</div><div class="comment-body"><div><span class="comment-author">'+(cu?cu.name:'Utente')+'</span><span class="comment-time">'+formatDate(c.createdAt)+'</span></div><div class="comment-text">'+c.text+'</div></div></div>';}).join(''):'<p style="color:var(--text3);font-size:13px;padding:8px 0">Nessun commento</p>')+'</div>'+(canComment?'<div class="comment-input-area"><textarea class="comment-textarea" id="newCommentText" placeholder="Scrivi un commento..."></textarea><button class="btn btn-primary" onclick="addComment(''+task.id+'')">💬 Invia</button></div>':'')+'</div>';
  var canEdit=task.createdBy===state.currentUser.id||state.currentUser.role==='manager';
  document.getElementById('detailFooter').innerHTML='<button class="btn btn-ghost" onclick="closeModal('detailModal')">Chiudi</button>'+(canEdit?'<button class="btn btn-ghost" onclick="editTask(''+task.id+'')">✏️ Modifica</button>':'')+'<button class="btn btn-ghost" onclick="openQuickReminder(''+task.id+'',event);closeModal('detailModal')" style="color:var(--warning)">🔔 Reminder</button><button class="btn btn-primary" onclick="toggleComplete(''+task.id+'',event);closeModal('detailModal')">'+(task.status==='completed'?'↩️ Riapri':'✅ Completa')+'</button>'+(canEdit?'<button class="btn btn-danger btn-sm" onclick="deleteTask(''+task.id+'',event);closeModal('detailModal')">🗑️</button>':'');
  openModal('detailModal');
}

function addComment(taskId){var text=document.getElementById('newCommentText').value.trim();if(!text){showNotif('Scrivi un commento','error');return;}var task=state.tasks.find(function(t){return t.id===taskId;});if(!task)return;if(!task.comments)task.comments=[];task.comments.push({id:'c'+Date.now(),userId:state.currentUser.id,text:text,createdAt:new Date().toISOString()});save();[task.createdBy,task.assignee,task.coAssignee,task.subAssignee].filter(Boolean).filter(function(uid){return uid!==state.currentUser.id;}).forEach(function(uid){addNotification(uid,'💬 '+state.currentUser.name+': "'+text.substring(0,50)+'"',taskId);});showNotif('Commento inviato!','success');openTaskDetail(taskId);}

function taskCard(t){var today=new Date();today.setHours(0,0,0,0);var isOv=t.status==='open'&&new Date(t.dueDate)<today;var a=getUserById(t.assignee),co=getUserById(t.coAssignee),sub=getUserById(t.subAssignee);var isUnread=a&&(!t.readBy||!t.readBy.includes(t.assignee))&&t.assignee!==state.currentUser.id;return'<div class="task-item '+(isOv?'overdue':'')+' '+(t.status==='completed'?'completed':'')+'" onclick="openTaskDetail(''+t.id+'')"><div class="task-check '+(t.status==='completed'?'done':'')+'" onclick="toggleComplete(''+t.id+'',event)"></div><div class="task-body"><div style="display:flex;align-items:center;gap:8px;margin-bottom:4px"><div class="task-title" style="margin-bottom:0">'+t.title+'</div>'+(isUnread?'<span class="unread-badge">● Non letto</span>':'')+'</div><div class="task-meta">'+dueDateTag(t.dueDate)+priorityTag(t.priority)+(a?'<span class="tag tag-assignee">👤 '+a.name.split(' ')[0]+'</span>':'')+(co?'<span class="tag" style="background:rgba(42,95,168,0.1);color:var(--accent3)">🤝 '+co.name.split(' ')[0]+'</span>':'')+(sub?'<span class="tag" style="background:rgba(232,98,26,0.1);color:var(--warning)">🔧 '+sub.name.split(' ')[0]+'</span>':'')+(t.list?'<span class="tag" style="background:var(--surface3);color:var(--text2)">📁 '+t.list+'</span>':'')+'</div></div><div class="task-actions"><button class="task-action-btn" onclick="openQuickReminder(''+t.id+'',event)">🔔</button><button class="task-action-btn" onclick="editTask(''+t.id+'');event.stopPropagation()">✏️</button><button class="task-action-btn" onclick="deleteTask(''+t.id+'',event)">🗑️</button></div></div>';}

function openQuickReminder(taskId,e){if(e)e.stopPropagation();var task=state.tasks.find(function(t){return t.id===taskId;});if(!task)return;var a=getUserById(task.assignee),co=getUserById(task.coAssignee),sub=getUserById(task.subAssignee);var rec=[a,co,sub].filter(Boolean).map(function(u){return u.name;}).join(', ');document.getElementById('qrTaskId').value=taskId;document.getElementById('qrMessage').value='';document.getElementById('qrTaskInfo').innerHTML='<div style="font-weight:600;color:var(--text);margin-bottom:6px">📋 '+task.title+'</div><div>📅 '+task.dueDate+'</div><div style="margin-top:4px">👤 '+rec+'</div>';openModal('quickReminderModal');}
function sendQuickReminder(){var taskId=document.getElementById('qrTaskId').value;var msg=document.getElementById('qrMessage').value.trim();var task=state.tasks.find(function(t){return t.id===taskId;});if(!task)return;var message=msg||'⏰ Reminder: "'+task.title+'" scade il '+task.dueDate;[task.assignee,task.coAssignee,task.subAssignee].filter(Boolean).forEach(function(uid){addNotification(uid,message,taskId);});closeModal('quickReminderModal');showNotif('🔔 Reminder inviato!','success');}

function showForgotPassword(){document.getElementById('forgotEmail').value='';document.getElementById('forgotNewPwd').value='';document.getElementById('forgotConfirmPwd').value='';document.getElementById('forgotStep2').style.display='none';document.getElementById('forgotError').style.display='none';document.getElementById('forgotBtn').textContent='Verifica →';openModal('forgotModal');}
function handleForgotPassword(){var email=document.getElementById('forgotEmail').value.trim();var step2=document.getElementById('forgotStep2');var errEl=document.getElementById('forgotError');errEl.style.display='none';if(step2.style.display==='none'){if(!email){errEl.textContent='Inserisci username';errEl.style.display='block';return;}var user=state.users.find(function(u){return u.email===email;});if(!user){errEl.textContent='Nessun account trovato';errEl.style.display='block';return;}step2.style.display='block';document.getElementById('forgotBtn').textContent='Salva →';}else{var pwd=document.getElementById('forgotNewPwd').value;var conf=document.getElementById('forgotConfirmPwd').value;if(pwd.length<6){errEl.textContent='Password troppo corta';errEl.style.display='block';return;}if(pwd!==conf){errEl.textContent='Le password non coincidono';errEl.style.display='block';return;}state.users.find(function(u){return u.email===email;}).password=pwd;save();closeModal('forgotModal');showNotif('✅ Password aggiornata!','success');}}

function getUserById(id){return state.users.find(function(u){return u.id===id;});}
function formatDate(iso){if(!iso)return'—';return new Date(iso).toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});}
function dueDateTag(dateStr){if(!dateStr)return'';var today=new Date();today.setHours(0,0,0,0);var d=new Date(dateStr);d.setHours(0,0,0,0);var diff=(d-today)/86400000;var cls=diff<0?'tag-date overdue':diff===0?'tag-date today':'tag-date';var label=diff<0?'⚠️ '+dateStr:diff===0?'⚡ Oggi':dateStr;return'<span class="tag '+cls+'">📅 '+label+'</span>';}
function priorityTag(p){var map={high:'tag-priority-high',medium:'tag-priority-med',low:'tag-priority-low'};var labels={high:'🔴 Alta',medium:'🟡 Media',low:'🟢 Bassa'};return'<span class="tag '+(map[p]||')')+'">'+( labels[p]||p)+'</span>';}
function applyFilter(tasks,f){var today=new Date();today.setHours(0,0,0,0);if(f==='open')return tasks.filter(function(t){return t.status==='open';});if(f==='completed')return tasks.filter(function(t){return t.status==='completed';});if(f==='overdue')return tasks.filter(function(t){return t.status==='open'&&new Date(t.dueDate)<today;});return tasks;}
function emptyState(title,sub){return'<div class="empty-state"><div class="icon">📭</div><p style="font-weight:600;color:var(--text2)">'+title+'</p>'+(sub?'<p>'+sub+'</p>':'')+'<button class="btn btn-primary" onclick="openNewTask()">+ Nuovo Task</button></div>';}
function openModal(id){document.getElementById(id).classList.add('open');}
function closeModal(id){document.getElementById(id).classList.remove('open');}
function showNotif(msg,type){type=type||'success';var area=document.getElementById('notifArea');var el=document.createElement('div');el.className='notif '+type;var icons={success:'✅',warning:'⚠️',error:'❌'};el.innerHTML='<span>'+(icons[type]||'ℹ️')+'</span><span>'+msg+'</span>';area.appendChild(el);setTimeout(function(){el.remove();},4000);}
function exportData(){var data={version:1,exported:new Date().toISOString(),users:state.users,tasks:state.tasks,notifications:state.notifications};var blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='taskflow_backup.json';a.click();showNotif('Backup esportato!','success');}
function importData(){var input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=function(e){var file=e.target.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(ev){try{var data=JSON.parse(ev.target.result);if(!data.users||!data.tasks){showNotif('File non valido!','error');return;}state.users=data.users;state.tasks=data.tasks;state.notifications=data.notifications||[];save();showNotif('Dati importati!','success');setTimeout(function(){location.reload();},1500);}catch(err){showNotif('Errore JSON','error');}};reader.readAsText(file);};input.click();}

window.addEventListener('DOMContentLoaded',function(){
  load();
  document.getElementById('btnLogin').addEventListener('click',doLogin);
  document.getElementById('btnRegister').addEventListener('click',doRegister);
  document.getElementById('loginEmail').addEventListener('keydown',function(e){if(e.key==='Enter')doLogin();});
  document.getElementById('loginPassword').addEventListener('keydown',function(e){if(e.key==='Enter')doLogin();});
  document.getElementById('regPassword').addEventListener('keydown',function(e){if(e.key==='Enter')doRegister();});
  document.querySelectorAll('.modal-overlay').forEach(function(m){m.addEventListener('click',function(e){if(e.target===m)m.classList.remove('open');});});
  var savedSession=localStorage.getItem('tfp_session');
  if(savedSession){var user=state.users.find(function(u){return u.id===savedSession;});if(user){state.currentUser=user;bootApp();}}
});
